PACKAGE_NAME="aivpn"
PACKAGE_VERSION="@VERSION@"
CLEAN="make clean"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
BUILT_MODULE_NAME[0]="aivpn"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/net/aivpn/"
STRIP[0]="no"
AUTOINSTALL="yes"
