import { authStore } from './stores/auth.svelte';
import { goto } from '$app/navigation';

// ─── Refresh coalescing ───────────────────────────────────────────────────────
// The refresh endpoint ROTATES the httpOnly refresh cookie. If several
// parallel requests hit 401 at once (dashboard fires 4+ queries on mount)
// and each starts its own POST /web/auth/refresh, the second refresh runs
// with the just-invalidated old cookie and logs the user out. Coalesce:
// only the first 401-caller starts a refresh; everyone else awaits the same
// in-flight promise. Reset on settle so a later 401 can refresh again.
let refreshPromise: Promise<string> | null = null;

/**
 * Mint a fresh access token from the httpOnly refresh cookie.
 * Concurrent callers share a single in-flight request.
 * Rejects if the refresh cookie is missing/expired/rotated away.
 */
export function refreshAccessToken(): Promise<string> {
  if (!refreshPromise) {
    refreshPromise = (async () => {
      const refreshRes = await fetch('/web/auth/refresh', { method: 'POST' });
      if (!refreshRes.ok) {
        throw new Error(`refresh failed: HTTP ${refreshRes.status}`);
      }
      const data = await refreshRes.json() as { access_token: string };
      authStore.setToken(data.access_token);
      return data.access_token;
    })().finally(() => {
      refreshPromise = null;
    });
  }
  return refreshPromise;
}

/** True when the body must be sent as-is (browser sets/derives Content-Type). */
function isRawBody(body: BodyInit | null | undefined): boolean {
  return (
    body instanceof Blob || // includes File
    body instanceof FormData ||
    body instanceof URLSearchParams ||
    body instanceof ArrayBuffer ||
    ArrayBuffer.isView(body as ArrayBufferView)
  );
}

async function apiFetch(path: string, options: RequestInit = {}): Promise<Response> {
  // Default to JSON only for string bodies (and body-less requests) — a
  // File/Blob/FormData upload must NOT be labeled application/json, and
  // FormData needs the browser-generated multipart boundary.
  const headers: Record<string, string> = {
    ...(isRawBody(options.body) ? {} : { 'Content-Type': 'application/json' }),
    ...(options.headers as Record<string, string> || {}),
  };

  if (authStore.accessToken) {
    headers['Authorization'] = `Bearer ${authStore.accessToken}`;
  }

  let res = await fetch(path, { ...options, headers });

  if (res.status === 401) {
    // Try refresh (coalesced across concurrent 401s)
    let newToken: string;
    try {
      newToken = await refreshAccessToken();
    } catch {
      authStore.clearToken();
      goto('/login');
      return res;
    }
    headers['Authorization'] = `Bearer ${newToken}`;
    res = await fetch(path, { ...options, headers });
    if (res.status === 401) {
      authStore.clearToken();
      goto('/login');
    }
  }

  return res;
}

async function apiJson<T>(path: string, options: RequestInit = {}): Promise<T> {
  const res = await apiFetch(path, options);
  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || `HTTP ${res.status}`);
  }
  return res.json() as Promise<T>;
}

export interface ClientQos {
  bandwidth_limit_up?: number;
  bandwidth_limit_down?: number;
  dscp_class?: string;
}

export interface Client {
  id: string;
  name: string;
  enabled: boolean;
  one_time: boolean;
  device_bound: boolean;
  vpn_ip: string;
  created_at: string;
  expires_at?: string | null;
  qos?: ClientQos;
  stats: {
    bytes_in: number;
    bytes_out: number;
    last_connected: string | null;
    total_connections: number;
    last_handshake: string | null;
  };
}

export interface AuditLogEntry {
  id: string;
  ts: string;
  actor: string;
  action: string;
  target: string;
  result: 'success' | 'error';
  detail?: string;
}

export interface Mask {
  id: string;
  file: string;
  size_bytes: number;
  modified: string | null;
  /** True when auto-generated by mask_gen from a recording (shown as "(авто)"). */
  generated: boolean;
}

export interface Metrics {
  cpu_percent: number;
  ram_used_mb: number;
  ram_total_mb: number;
  load_avg: number;
}

export interface ServerStatus {
  uptime_seconds: number;
  version: string;
  connected_clients: number;
  total_clients: number;
  kernel_loaded: boolean;
}

export interface KernelStatus {
  loaded: boolean;
  version?: string;
  error?: string;
}

export const auth = {
  async login(username: string, password: string): Promise<{ access_token?: string; totp_required?: boolean }> {
    return apiJson('/web/auth/login', {
      method: 'POST',
      body: JSON.stringify({ username, password }),
    });
  },
  async loginTotp(username: string, password: string, totp_token: string): Promise<{ access_token: string }> {
    return apiJson('/web/auth/login', {
      method: 'POST',
      body: JSON.stringify({ username, password, totp_token }),
    });
  },
  async logout(): Promise<void> {
    await apiFetch('/web/auth/logout', { method: 'POST' });
  },
  async me(): Promise<{ id: string; username: string; role: string; totp_enabled: boolean }> {
    return apiJson('/web/auth/me');
  },
  async changePassword(current_password: string, new_password: string): Promise<void> {
    await apiJson('/web/auth/change-password', {
      method: 'POST',
      body: JSON.stringify({ current_password, new_password }),
    });
  },
  async totpSetup(): Promise<{ secret: string; otpauth_url: string; qr_data_url: string }> {
    return apiJson('/web/auth/totp/setup');
  },
  async totpVerify(token: string): Promise<void> {
    await apiJson('/web/auth/totp/verify', {
      method: 'POST',
      body: JSON.stringify({ token }),
    });
  },
  async totpDelete(): Promise<void> {
    await apiFetch('/web/auth/totp', { method: 'DELETE' });
  },
  async passkeyRegistrationOptions(): Promise<unknown> {
    return apiJson('/web/auth/passkey/registration-options');
  },
  async passkeyRegister(response: unknown, name: string): Promise<void> {
    await apiJson('/web/auth/passkey/register', {
      method: 'POST',
      body: JSON.stringify({ response, name }),
    });
  },
  async passkeyAuthOptions(username?: string): Promise<unknown> {
    const q = username ? `?username=${encodeURIComponent(username)}` : '';
    return apiJson(`/web/auth/passkey/authentication-options${q}`);
  },
  async passkeyAuthenticate(response: unknown): Promise<{ access_token: string }> {
    return apiJson('/web/auth/passkey/authenticate', {
      method: 'POST',
      body: JSON.stringify({ response }),
    });
  },
  async passkeys(): Promise<Array<{ id: string; name: string; created_at: string; last_used_at: string | null }>> {
    return apiJson('/web/auth/passkeys');
  },
  async passkeyDelete(id: string): Promise<void> {
    await apiFetch(`/web/auth/passkeys/${id}`, { method: 'DELETE' });
  },
  async sessions(): Promise<Array<{ id: string; ip: string | null; ua: string | null; created_at: string; expires_at: string; current: boolean }>> {
    return apiJson('/web/auth/sessions');
  },
  async sessionDelete(id: string): Promise<void> {
    await apiFetch(`/web/auth/sessions/${id}`, { method: 'DELETE' });
  },
  async sessionsDeleteAll(): Promise<void> {
    await apiFetch('/web/auth/sessions', { method: 'DELETE' });
  },
};

export const metrics = {
  async get(): Promise<Metrics> {
    return apiJson('/web/metrics');
  },
};

export const status = {
  async get(): Promise<ServerStatus> {
    return apiJson('/api/v1/status');
  },
};

export const clients = {
  async list(params?: { search?: string; enabled?: boolean; page?: number; limit?: number }): Promise<{ items: Client[]; total: number }> {
    const q = new URLSearchParams();
    if (params?.search) q.set('search', params.search);
    if (params?.enabled !== undefined) q.set('enabled', String(params.enabled));
    if (params?.page !== undefined) q.set('page', String(params.page));
    if (params?.limit !== undefined) q.set('limit', String(params.limit));
    const raw = await apiJson<Client[] | { items: Client[]; total: number }>(`/api/v1/clients?${q}`);
    // Server returns plain array; normalise to paginated shape
    if (Array.isArray(raw)) return { items: raw, total: raw.length };
    return raw as { items: Client[]; total: number };
  },
  async get(id: string): Promise<Client> {
    return apiJson(`/api/v1/clients/${id}`);
  },
  async create(data: { name: string; one_time?: boolean; expires_at?: string | null; qos?: ClientQos }): Promise<Client> {
    return apiJson('/api/v1/clients', { method: 'POST', body: JSON.stringify(data) });
  },
  async update(id: string, data: { name?: string; enabled?: boolean; one_time?: boolean; expires_at?: string | null; qos?: ClientQos | null }): Promise<Client> {
    return apiJson(`/api/v1/clients/${id}`, { method: 'PATCH', body: JSON.stringify(data) });
  },
  async delete(id: string): Promise<void> {
    await apiFetch(`/api/v1/clients/${id}`, { method: 'DELETE' });
  },
  async connectionKey(id: string): Promise<{ connection_key: string }> {
    return apiJson(`/api/v1/clients/${id}/connection-key`);
  },
  async resetDevice(id: string): Promise<void> {
    await apiFetch(`/api/v1/clients/${id}/reset-device`, { method: 'POST' });
  },
};

export const config = {
  async get(): Promise<Record<string, unknown>> {
    return apiJson('/api/v1/config');
  },
  async update(data: Record<string, unknown>): Promise<Record<string, unknown>> {
    return apiJson('/api/v1/config', { method: 'PUT', body: JSON.stringify(data) });
  },
};

export const masks = {
  async list(): Promise<Mask[]> {
    return apiJson('/api/v1/masks');
  },
  async upload(name: string, content: string): Promise<void> {
    await apiFetch(`/api/v1/masks?name=${encodeURIComponent(name)}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: content,
    });
  },
  async delete(name: string): Promise<void> {
    await apiFetch(`/api/v1/masks/${encodeURIComponent(name)}`, { method: 'DELETE' });
  },
};

export const auditLog = {
  async list(limit = 200): Promise<AuditLogEntry[]> {
    return apiJson(`/api/v1/audit-log?limit=${limit}`);
  },
};

export const kernel = {
  async get(): Promise<KernelStatus> {
    return apiJson('/api/v1/kernel');
  },
};

export const reload = {
  async trigger(): Promise<void> {
    await apiFetch('/api/v1/reload', { method: 'POST' });
  },
};

export const events = {
  /**
   * Mint a short-lived single-use SSE ticket via an authenticated POST.
   * EventSource cannot set an Authorization header, so the ticket (NOT the
   * general access token) is what goes into the /web/events URL. Each ticket
   * is consumed on connect — mint a fresh one for every (re)connect.
   */
  async ticket(): Promise<string> {
    const data = await apiJson<{ ticket: string }>('/web/events/ticket', { method: 'POST' });
    return data.ticket;
  },
};

export { apiFetch };
